### ISSUE TITLE
armcc.exe - Unhandled function EnumSystemLocalesA (KERNEL32.dll)

### ISSUE THREAD

**Issue by mkst** [decompals/wibo#62]
Passing the `--locale=XXXX` flag to `armcc.exe` results in the titular error.

It feels like it will be a lot of work to properly implement locales, so perhaps we can add a reasonable hack (and emit a warning that locales are not really supported)?

**Comment by ConorBobbleHat** [comment]
Apologies if this is known already, but for the sake of documentation - it seems like some versions (armcc_41_894, armcc_41_1049, and armcc_41_713) still aren't happy. All the failures look something like:
```
~/projects/wibo-clean/wibo/build/wibo armcc.exe --locale=japanese test.c
"no source": Error:  #869: could not set locale "japanese" to allow processing of multibyte characters
test.c: 0 warnings, 1 error
```

**Comment by mkst** [comment]
I think it's in the discord, but good to have that comment here too. You see absolutely correct that locales are not supported - but now you get the error message you saw, rather than "Unhandled function EnumSystemLocalesA". I don't know how the effort/reward chart looks like if we wanted to properly support locales?
