### ISSUE TITLE
ProDG (cc1.exe) Segmentation Fault on large input w/ optimisation (i.e. -O1)

### ISSUE THREAD

**Issue by mkst** [decompals/wibo#64]
Enabling optimisations on [this](https://decomp.me/scratch/m6Rym.) scratch causes a Segmentation Fault. The export of the scratch is attached to this issue: [DrawPanel.zip](https://github.com/decompals/wibo/files/13479562/DrawPanel.zip).

The segfault does not occur under wine.

When running locally, the last few lines of the debug log are:
```
HeapFree(heap=0x100006, flags=0, mem=0x7fd98010)
HeapFree(heap=0x100006, flags=0, mem=0x7fd98070)
HeapFree(heap=0x100006, flags=0, mem=0x7fd98040)
HeapFree(heap=0x100006, flags=0, mem=0x7fd980a0)
HeapFree(heap=0x100006, flags=0, mem=0x7fd980d0)
HeapFree(heap=0x100006, flags=0, mem=0x7fffd920)
HeapFree(heap=0x100006, flags=0, mem=0x7fdac090)
GetSystemTimeAsFileTime
GetSystemTimeAsFileTime
GetSystemTimeAsFileTime
GetSystemTimeAsFileTime
HeapAlloc(heap=0x100006, flags=0, bytes=15200) -> 0x7fdaa330
HeapAlloc(heap=0x100006, flags=0, bytes=4080) -> 0x7fdcceb0
HeapAlloc(heap=0x100006, flags=0, bytes=30912) -> 0x7fda20a0
```

Full debug log is here: [segfault.log](https://github.com/decompals/wibo/files/13479596/segfault.log)

**Comment by simonlindholm** [comment]
With consecutive HeapAlloc and HeapFree compressed and GetSystemTimeAsFileTime removed (still not very illuminating): [segfault2.log](https://github.com/decompals/wibo/files/13480937/segfault2.log)
